apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.app }}-{{ .Values.name }}-{{ .Values.technology }}-{{ .Values.system }}-{{ .Values.env }}-{{ .Values.image.tag }}-settings-v201"
data:
  settings.ini: |
    # possible values : production, development, staging, qa
    app_mode = {{ .Values.appMode }}

    [security]
    # Path to SSL certificates
    certificates = {{ .Values.certificatePath }}

    [paypal]
    paypal_url = {{ .Values.paypalURLLocation }}

    [mysql]
    db_user = {{ .Values.databaseUser }}
    db_password = {{ .Values.databasePassword }}



